echo "my name is bhanu"
echo "i am learning github"
echo "i a working in Jpmchase"
echo "i live in mumbai"
echo "will drink beer"
echo "aroli sector -9"
echo "jai Jaganath"
echo "i was living at rkl"
echo "deployment"
echo "This is new branch"
echo "Today Saturdayyy"
